import "./globals.css";
import type { Metadata } from "next";
import { headers } from "next/headers";

import { cookieToInitialState } from "wagmi";

import { config } from "@/config";
import Web3ModalProvider from "@/context";
import { gtText } from "@/components/Fonts";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const initialState = cookieToInitialState(config, headers().get("cookie"));
	return (
		<html lang="en">
			<body className={gtText.className}>
				<Web3ModalProvider initialState={initialState}>
					<Navbar />
					<div className="py-6">{children}</div>
				</Web3ModalProvider>
			</body>
		</html>
	);
}
